server:
  port:8080

spring:
  application:
    name: springBootProject1
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1522/ORCL19
    username: C##kin412
    password: 1234
  thymeleaf:
    cache: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: firstJob

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update